### PR TITLE
Update Q to 1.1.2

### PR DESCRIPTION
**Pull request by tadatuta**
Checked update with internal tests and within `bem-tools`. Everything works as before.

### CODE REVIEW

**Comment by shinnn** [comment]
@veged Could you release a new patch-updated version? I'd like to use the version including this change.

**Comment by veged** [comment]
@shinnn the bump was from `~0.9.6` to `^1.1.2`, so accordingly SemVer I can only release minor version — is it ok for you?

**Comment by shinnn** [comment]
@veged Ah, sorry I was wrong. Minor version is ok.

**Comment by veged** [comment]
@shinnn sorry, me wrong too — it should be major version (cause Q was bumped to major)

**Comment by veged** [comment]
@shinnn done

**Pull request merged**
